// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "squirrel":return img`
.....................................
......fffff....................f.....
....ffeeeeeff..........ff.....fef....
...feeeeeeeeef........f3ff....feef...
..feeeeeeeeeeef.......f3feffffffef...
.f111eeeeeeeeeef......f3feeeeeeeff...
..ff11eeeeeeeeef.......ffeeeeeeeeef..
....f11eeeeeeeeef.....feeeeeeeeeeef..
....f11eeeeeeeeef.....feeeeeeeeeeeff.
....f11eeeeeeeeef....feeeeeeffeeeeff.
....f11eeeeeeeeef....feeeeeeffeeeeef.
....f11eeeeeeeeef...feeeeeeeeee1ff1f.
....f11eeeeeeeeef..feeeefeeeee111f1f.
....f11eeeeeeeef..feeeeeefeeee1ffff..
....f11eeeeeeeef.feeeeeeeefeeee11f...
....f11eeeeeeeeffeeeeeeee11ffffff....
....f11eeeeeeeefeeeeefee1111111ef....
....f11eeeeeeefeeeeefeee111111eeef...
....f11eeeeeeefeeeeefeeee1f111feef...
.....f1eeeeeefeeeeeeefeeeeef1feeef...
.....f11eeeeefeeeeeeeeffeeeefeeef....
.....f111eeeefeeeeeee111ffeefeef.....
......f11eeeefeeeeee111111ff1ff......
......f11eeeefeeeeee1111111111f......
.......f1eeeefeeeee11111111111f......
.......f11eeefeeeee11111111111ef.....
........f11eeefeeee11111111111ef.....
.........f11eefeeee11111111111ef.....
..........ff111feee11111111111ef.....
............ffffeeee1f1111f11ef......
................feeeef111f11eef......
................feeeefffff11eef......
.................feeef....feef.......
..................fff......feef......
..................feef.....feeef.....
..................feeef.....ffff.....
...................feef..............
....................ff...............
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
